apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chat-app
spec:
  selector:
    app: backend
  ports:
  - port: 5001        #jithe aapn bagnr to
    targetPort: 5001  #container port